Insert into products (Name, Cost) values ('Clorox', 12.50);
Insert into products (Name, Cost) values ('Pantene Shampooo', 32.50);
Insert into products (Name, Cost) values ('Strawberry', 10.99);
Insert into products (Name, Cost) values ('Olay Body Wash', 9.79);
Insert into products (Name, Cost) values ('L\'Oreal', 7.69);
Insert into products (Name, Cost) values ('Dettol Handwash', 5.39);
Insert into products (Name, Cost) values ('Milk', 2.5);
Insert into products (Name, Cost) values ('Bluetooth Speaker', 49.99);
Insert into products (Name, Cost) values ('Snickers', 1.39);
Insert into products (Name, Cost) values ('Bounty', 29.99);
Insert into products (Name, Cost) values ('Charmin', 27.89);
Insert into products (Name, Cost) values ('AirPods', 139.99);
Insert into products (Name, Cost) values ('EarPods', 29.99);
Insert into products (Name, Cost) values ('Razer BlackWidow Mouse', 30.00);
Insert into products (Name, Cost) values ('Razer BlackWidow KeyBoard', 79.99);
Insert into products (Name, Cost) values ('Apple iPhone Xs', 999.99);

Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 1);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 1);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 2);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 2);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 3);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 3);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 4);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 4);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 5);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 5);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 6);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 6);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 7);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 7);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 8);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 8);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 9);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 9);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 10);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 10);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 11);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 11);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 12);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 12);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 13);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 13);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 14);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 14);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 15);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 15);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 16);
Insert into reviews (subject, review_text, products_id) values ('Review', 'This is a review', 16);

Insert into comments (comment_text, reviews_id) values ('This is a comment', 1);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 1);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 2);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 2);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 3);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 3);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 4);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 4);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 5);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 5);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 6);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 6);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 7);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 7);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 8);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 8);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 9);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 9);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 10);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 10);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 11);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 11);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 12);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 12);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 13);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 13);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 14);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 14);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 15);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 15);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 16);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 16);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 17);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 17);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 18);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 18);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 19);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 19);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 20);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 20);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 21);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 21);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 22);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 22);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 23);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 23);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 24);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 24);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 25);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 25);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 26);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 26);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 27);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 27);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 28);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 28);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 29);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 29);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 30);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 30);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 31);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 31);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 32);
Insert into comments (comment_text, reviews_id) values ('This is a comment', 32);